language: python
python: 3.5

addons:
  apt_packages:
    - pandoc

install:
  - pip install .
script:
  - rtifact --version

before_deploy:
  - pip install pypandoc

deploy:
  provider: pypi
  user: randy3k
  password:
    secure: NN8JFjYnhGzllpmfsCxsxmBuvj+zgzOiA0z82bkUcrNauWu+TcsK1ydbDGzOQ9MeCQgp9G8oLfd9jC0sv6PdcUoR7T+HLYd4pgLjBvy204MEOrnhYlm9PmXW4xXh1GNB+0027ieTocsHeYyKb8Teqoaygq3fNlZjXo9roFo55woGm5pb9WhWG2TyKSDBV/ynSnsruASLnyU9rYOkNgd1HXiqBSo9fKYntFLt8iSoYPS/0xTdw2FtO+VUlOutEWKukdoIHqodKqJalSpFcvPUqjohbCavQ/oXFE/1KRvw7gcoXEa8/ZnduYmp8jppT2SFIxdx4qGJ0yBM4OxPL8pAhxEfUUCPwTuKQa93d1+kHV0dBkzxilqwJVu7OCki9ysLyeAUjPEVCHHigTo9oH53Kgm4oJC5tekETRpML1buGz+ZHKScmyjMZyAXSjF2sPs7Wzwga2JPY2pAyTW86o4VfMlTSxuxOuoCwun/gMsiiOjN9MJrnKbM/I+xNFBK2haQZAWIVHos/mvH2+sT97msWFh4voLAm7H3WKt2cs0MG3wHwWZ7+C0MHn42GlVW53bs12ruEsE3xGnL2upwYztSCjFEBOt87rG+pTdLM2kJqxty92opva2M5REFAKBWL8vC85+lCANS7BHHO0rYdfeL2ZcnZDxo0FDyGxm5nz9jTJA=
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: change
